### ISSUE TITLE
PID was found or no process is running there

### ISSUE THREAD

**Issue by StarpTech** [bitnami/bitnami-docker-mongodb#20] opened 2016-06-18 13:30 UTC
I get this error messag when I try to persistent my database:

```
harpoon ERROR Unable to start com.bitnami.mongodb: Pid file '/opt/bitnami/mongodb/tmp/mongodb.pid' was found but either no proper PID was found or no process is running there.
```

cocker-compose:

```
mongo:
  image: bitnami/mongodb:latest
  container_name: mongo
  hostname: mongo
  volumes:
    - ./data/mongo:/bitnami/mongodb
  restart: always
  ports:
    - "27017:27017"
```

Thank you.

**Comment by sameersbn** [comment] 2016-06-18 15:10
@StarpTech I tried your docker-compose.yml file and found it to be working. Can you please share the output of the following commands?

- `uname -a`
- `docker version`
- `docker-compose version`
- `docker-machine version`
- `docker run -it --rm bitnami/mongodb:latest printenv | grep BITNAMI_`
- `docker run -it --rm bitnami/mongodb:latest uname -a`

Also are you using `docker-machine`, `boot2docker`, etc. for creating the containers in a VM?

**Comment by jedielson** [comment] 2016-10-27 18:47
Hi, I had de same problem here...

I'm using windows: Microsoft Windows [10.0.14393]

docker info
```
Containers: 1                                                                                    
 Running: 0                                                                                      
 Paused: 0                                                                                       
 Stopped: 1                                                                                      
Images: 20                                                                                       
Server Version: 1.12.1                                                                           
Storage Driver: aufs                                                                             
 Root Dir: /var/lib/docker/aufs                                                                  
 Backing Filesystem: extfs                                                                       
 Dirs: 117                                                                                       
 Dirperm1 Supported: true                                                                        
Logging Driver: json-file                                                                        
Cgroup Driver: cgroupfs                                                                          
Plugins:                                                                                         
 Volume: local                                                                                   
 Network: bridge null host overlay                                                               
Swarm: inactive                                                                                  
Runtimes: runc                                                                                   
Default Runtime: runc                                                                            
Security Options: seccomp                                                                        
Kernel Version: 4.4.20-moby                                                                      
Operating System: Alpine Linux v3.4                                                              
OSType: linux                                                                                    
Architecture: x86_64                                                                             
CPUs: 2                                                                                          
Total Memory: 1.92 GiB                                                                           
Name: moby                                                                                       
ID: 7HMJ:DT7D:JGYK:JFES:6CQH:TXBG:G7ZT:LUIQ:X4MC:5Z6H:B6WO:LTKN                                  
Docker Root Dir: /var/lib/docker                                                                 
Debug Mode (client): false                                                                       
Debug Mode (server): true                                                                        
 File Descriptors: 13                                                                            
 Goroutines: 23                                                                                  
 System Time: 2016-10-27T17:26:47.6991522Z                                                       
 EventsListeners: 0                                                                              
Registry: https://index.docker.io/v1/                                                            
Insecure Registries:                                                                             
 127.0.0.0/8                                                                                     
```
docker version
```
Client:                                   
 Version:      1.12.1                     
 API version:  1.24                       
 Go version:   go1.6.3                    
 Git commit:   23cf638                    
 Built:        Thu Aug 18 17:52:38 2016   
 OS/Arch:      windows/amd64              
                                          
Server:                                   
 Version:      1.12.1                     
 API version:  1.24                       
 Go version:   go1.6.3                    
 Git commit:   23cf638                    
 Built:        Thu Aug 18 17:52:38 2016   
 OS/Arch:      linux/amd64                

```
docker-compose version
```
docker-compose version 1.8.0, build d988a55
docker-py version: 1.9.0
CPython version: 2.7.11
OpenSSL version: OpenSSL 1.0.2d 9 Jul 2015
```
docker-machine version

`docker-machine.exe version 0.8.1, build 41b3b25`

docker run -it --rm bitnami/mongodb:latest printenv | grep BITNAMI_

```
BITNAMI_APP_NAME=mongodb
BITNAMI_APP_USER=mongo
BITNAMI_IMAGE_VERSION=3.2.10-r0
```

docker run -it --rm bitnami/mongodb:latest uname -a

`Linux 3a20c0cab057 4.4.20-moby #1 SMP Thu Sep 15 12:10:20 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`

And here is my docker-compose.yml

``` yml
version: '2'
services:
  mongodb:
    container_name: my-mongodb
    image: bitnami/mongodb:latest
    volumes:
      - 'C:/DockerStore/mongodb:/bitnami/mongodb'
    ports:
      - '27017:27017'
    environment:
      - MONGODB_ROOT_PASSWORD=jedi
```

Apparently, the problem happens because of ports...

If you create mannualy, the port is set to 21017, but when you use docker-compose does not works.

**Comment by jedielson** [comment] 2016-11-04 17:09
Hi!

Any update on it?

**Comment by karneaud** [comment] 2016-12-21 01:50
+1 bump

**Comment by prydonius** [comment] 2016-12-21 01:54
Can you confirm if MongoDB works as expected when you remove the mounted volume in your Compose file?

**Comment by karneaud** [comment] 2016-12-21 02:15
it work by exposing the ports

**Comment by joel611** [comment] 2016-12-28 09:43
Should be the volume mounting problem.
https://docs.docker.com/engine/tutorials/dockervolumes/
Docker for window only can mount folder under C:\Users and you are trying to mount on C:/DockerStore/mongodb.

**Comment by jedielson** [comment] 2016-12-28 15:55
I don't think it is...
First, because on windows, we must flag the option of share C:/.
Second, because I have others containers like redmine and mariaDB running on my machine, and all volumes are being mounted on C:/DockerStore/<appName>.

As I've said before, when I use my "ports" instruction on the yml, the problem occurs...

**Comment by ArnaudRinquin** [comment] 2016-12-28 18:09
I have the same PID related issue running the image in a kubernetes cluster.

Here are the logs I get from any replica mode (`primary`, `secondary`, `arbiter`):

```
nami    INFO  Initializing mongodb
mongodb INFO  ==> Creating collab-mongo-user user...
mongodb INFO  ==> Enabling authentication...
mongodb INFO  ==> Writing keyfile for replica set authentication
mongodb INFO  ==> Configuring MongoDB replica set
Error executing 'postInstallation': Unable to start com.bitnami.mongodb: Pid file '/opt/bitnami/mongodb/tmp/mongodb.pid' was found but either no proper PID was found or no process is running there.: Pid file '/opt/bitnami/mongodb/tmp/mongodb.pid' was found but either no proper PID was found or no process is running there.
```

**Comment by ArnaudRinquin** [comment] 2016-12-29 10:51
@sameersbn I'd like to debug this a bit but can't go much further without help.

Could you please point where the `postInstallation` script outputting the following error  is, how I can debug it, etc? Thanks 🙏 .

```sh
Error executing 'postInstallation': Unable to start com.bitnami.mongodb: Pid file '/opt/bitnami/mongodb/tmp/mongodb.pid' was found but either no proper PID was found or no process is running there.: Pid file '/opt/bitnami/mongodb/tmp/mongodb.pid' was found but either no proper PID was found or no process is running there.
```

**Comment by sameersbn** [comment] 2016-12-29 11:13
You can add the argument `--log-level trace8` to the command https://github.com/bitnami/bitnami-docker-mongodb/blob/master/rootfs/app-entrypoint.sh#L12 to displaty debug information

**Comment by ArnaudRinquin** [comment] 2016-12-29 11:14
Thanks!

**Comment by sameersbn** [comment] 2016-12-29 11:15
Sorry that this issue has been open for so long. I will setup an window 10 vm and try to debug the issue as well.

**Comment by sameersbn** [comment] 2016-12-29 11:19
yes please share the chart files, it would help a lot.
btw, have tou tried the bitnami contributed mongodb chart https://github.com/kubernetes/charts/tree/master/stable/mongodb?

**Comment by ArnaudRinquin** [comment] 2016-12-29 11:21
I started with the official chart but I need to setup a replicaSet which I don't think the official chart lets me do.

**Comment by sameersbn** [comment] 2016-12-29 11:24
thats right.. we're working on a chart to support redis replicasets. 
Can you share your chart files to debug the issue?

**Comment by ArnaudRinquin** [comment] 2016-12-29 11:27
[Here](https://gist.github.com/ArnaudRinquin/c3656375a0c1504203eb8f9398d9b4c1) you go!

**Comment by sameersbn** [comment] 2016-12-29 11:32
thanks but could you share the chart archive so i can try to deploy it right away?

**Comment by ArnaudRinquin** [comment] 2016-12-29 11:37
Oh never made an archive. I just zipped [all the files](https://www.dropbox.com/s/sao9ynhpy5ntut1/collab.zip?dl=1). I hope it's enough.

**Comment by jedielson** [comment] 2016-12-29 12:09
Thanks @sameersbn! :)

**Comment by ArnaudRinquin** [comment] 2016-12-29 13:06
With the `--log-level trace8` debug on, I can see that the container infinite-loops on:

```
mongodb TRACE [normalize] File normalization: /opt/bitnami/mongodb/tmp/mongodb.pid -> /opt/bitnami/mongodb/tmp/mongodb.pid
mongodb TRACE [normalize] File normalization: tmp -> /opt/bitnami/mongodb/tmp
mongodb TRACE [normalize] File normalization: /opt/bitnami/mongodb/tmp/mongodb.pid -> /opt/bitnami/mongodb/tmp/mongodb.pid
mongodb TRACE [normalize] File normalization: tmp -> /opt/bitnami/mongodb/tmp
```

**Comment by ArnaudRinquin** [comment] 2016-12-29 13:17
Where is the source code for the `nami` bundle (not sure about the wording here) executed in:

`CMD ["nami", "start", "--foreground", "mongodb"]`

**Comment by ArnaudRinquin** [comment] 2016-12-29 13:25
> nami is available as opensource software https://github.com/bitnami/nami

Has I understand it, `nami` runs a described bundle, here `mongodb`

Where can I find these `mongodb` nami json and js description file?

**Comment by sameersbn** [comment] 2016-12-29 13:32
you can use the `bitnami-pkg` tool from the image to download the module and extract it. have a look at the Dockerfile

**Comment by sameersbn** [comment] 2016-12-30 04:52
@ArnaudRinquin I tested the chart on a kubernetes cluster created on google container engine and did not face any issues. Can you please describe how your kubernetes cluster is setup. Is it possible that docker on the cluster nodes are using the overlayfs filesystem? Because we have been seeing weird problems with this storage driver (https://github.com/bitnami/bitnami-docker-testlink/issues/17#issuecomment-261783035).

**Comment by ArnaudRinquin** [comment] 2016-12-30 09:17
> Can you please describe how your kubernetes cluster is setup. Is it possible that the cluster nodes are using the overlayfs storage driver for docker?

I'm not sure how to check that but here is a screenshot from "Google Cloud Platform → Compute Engine → Disks":

<img width="984" alt="screen shot 2016-12-30 at 10 14 04" src="https://cloud.githubusercontent.com/assets/228886/21562414/0f9047f2-ce79-11e6-9eaa-ed4066ae6aaa.png">

**Comment by sameersbn** [comment] 2016-12-30 13:48
@jedielson Hi. `mongod` server has compatibility issues with the shared filesystem on Docker for Windows. It probably expects a unix compatible filesystem.

In the following logs this is a little clear.

```
2016-12-30T12:18:50.851+0000 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=470M,session_max=20000,eviction=(threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),checkpoint=(wait=60,log_size=2GB),statistics_log=(wait=0),
2016-12-30T12:18:50.903+0000 E STORAGE  [initandlisten] WiredTiger error (1) [1483100330:903378][1:0x7fda89dc7cc0], connection: /opt/bitnami/mongodb/data/db/WiredTiger.wt: handle-open: open: Operation not permitted
2016-12-30T12:18:50.906+0000 I -        [initandlisten] Assertion: 28595:1: Operation not permitted src/mongo/db/storage/wiredtiger/wiredtiger_kv_engine.cpp 267
2016-12-30T12:18:50.907+0000 I STORAGE  [initandlisten] exception in initAndListen: 28595 1: Operation not permitted, terminating
2016-12-30T12:18:50.907+0000 I NETWORK  [initandlisten] shutdown: going to close listening sockets...
2016-12-30T12:18:50.907+0000 I NETWORK  [initandlisten] removing socket file: /tmp/mongodb-27017.sock
2016-12-30T12:18:50.907+0000 I NETWORK  [initandlisten] shutdown: going to flush diaglog...
2016-12-30T12:18:50.907+0000 I CONTROL  [initandlisten] now exiting
2016-12-30T12:18:50.907+0000 I CONTROL  [initandlisten] shutting down with code:100
```

This problem is not seen if the host `volume` mounts are removed from the `docker-compose.yml` spec. I do not see any issue with the exposed ports.

I used the following spec for the tests

```yaml
mongo:
  image: bitnami/mongodb:latest
  container_name: mongo
  hostname: mongo
  volumes:
    - ./data/mongo:/bitnami/mongodb
  restart: always
  ports:
    - "27017:27017"
```

**Comment by sameersbn** [comment] 2017-01-09 13:54
Hi @ArnaudRinquin 

There seems to be an issue configuring authentication in mongodb while configuring replicasets. At the moment the work around is to avoid using authentication for this use case. We are working on fixing the issue and provide an update soon.

In the mean time you can disable the user creation and setting of the root password to workaround this issue. You can apply this [patch](https://dl.dropboxusercontent.com/u/45559595/bitnami-docker-mongodb-issue-20/workaround.patch) which has the required changes over what you shared earlier. Here is the complete archive of the same https://dl.dropboxusercontent.com/u/45559595/bitnami-docker-mongodb-issue-20/collab.tar.bz2.

We apologize of the inconvenience and are working hard to resolve this issue.

Please do reach out to us if you need any additional help.

Best Regards
~Sameer

**Comment by ArnaudRinquin** [comment] 2017-01-09 13:55
Thanks for the work! I'll use the workaround for now and make sure to keep an eye on this issue.

**Comment by sameersbn** [comment] 2017-01-10 05:59
@ArnaudRinquin continuing with my investigation the cause of the issue was the value of the `MONGODB_REPLICA_SET_KEY` parameter. This value should be an alphanumeric string of length greater than 5 characters and cannot contain any special characters. The default value that was set in the chart is `collab-replica-set-key` which does not fit these constraints which caused the mongod server initialization to error out. Unfortunately this error is not being communicated to the user. We need to improve the image to make the logs visible to the user. 

Moving on with your use case, since the issue was not really related to enabling authentication as i previously suggested, you can enable authentication on mongo server as you desired. Please find the [changes](https://dl.dropboxusercontent.com/u/45559595/bitnami-docker-mongodb-issue-20/fixes.patch) and the complete chart [archive](https://dl.dropboxusercontent.com/u/45559595/bitnami-docker-mongodb-issue-20/collab.tar.bz2). I have made minimal changes to your chart. However I will note that you should consider prefixing the chart release name to the deployed kubernetes components (pods, svcs, etc.) to ensure that the same chart can be deployed more than once in the same kubernetes cluster.

Do reach out to us if you have further questions.

**Comment by ArnaudRinquin** [comment] 2017-01-10 08:32
Ah nice! 👏  for the thorough investigation! 

Thanks a lot @sameersbn

**Comment by sameersbn** [comment] 2017-01-25 05:24
Closing this issue as it appears to be a filesystem compatibility issue with Docker on Windows as pointed  out in my comment here https://github.com/bitnami/bitnami-docker-mongodb/issues/20#issuecomment-269773493

**Closed by sameersbn** 2017-01-25 05:24 UTC
Labels: wontfix

**Comment by jedielson** [comment] 2017-01-25 13:08
@sameersbn 
Ok. Thanks for your help!!!
