### ISSUE TITLE
make ipv6 a settable parameter

### ISSUE THREAD

**Issue by ebalsumgo** [bitnami/bitnami-docker-mongodb#108] opened 2018-08-16 18:41 UTC
**Description**

I am having issues running the official mongodb helm charts because my system explicitly disables IPV6 and when mongo goes to start 
`2018-08-16T18:23:31.408+0000 I CONTROL  [initandlisten] options: { config: "/opt/bitnami/mongodb/conf/mongodb.conf", net: { bindIpAll: true, ipv6: true, port: 27017, unixDomainSocket: { enabled: true, pathPrefix: "/opt/bitnami/mongodb/tmp" } }, processManagement: { fork: false, pidFilePath: "/opt/bitnami/mongodb/tmp/mongodb.pid" }, replication: { replSetName: "rs0" }, security: { authorization: "enabled", keyFile: "/opt/bitnami/mongodb/conf/keyfile" }, setParameter: { enableLocalhostAuthBypass: "true" }, storage: { dbPath: "/opt/bitnami/mongodb/data/db", journal: { enabled: true } }, systemLog: { destination: "file", logAppend: true, path: true } }
2018-08-16T18:23:31.419+0000 I STORAGE  [initandlisten] exception in initAndListen std::exception: open: Address family not supported by protocol, terminating`
It fails.

**Steps to reproduce the issue:**

1. Disable ipv6 in kernel
2. helm install stable/mongodb -f value-production.yaml
3. kube logs <release-mongo>

**Describe the results you received:**

The primary and secondary nodes keep crashing because they cannot start up.

**Describe the results you expected:**

Have mongo fire up

**Additional information you deem important (e.g. issue happens only occasionally):**

If i can pass a parameter either to the docker image or to the helm chart to disable ipv6 i should be able to start up on a system with it explicitly disabled

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
physical k8s cluster

**Comment by tompizmor** [comment] 2018-08-17 09:15
I agree with you Juan! 
IPv6 can still be enabled by default but it would be nice to allow disabling it. Although, it is also true that anyone can provide their custom configuration file so I don't really have a strong opinion.

**Comment by sameersbn** [comment] 2018-08-17 09:16
This is weird. I remember testing the settings suggested in #97 on a cluster that has ip v6 disabled and did not encounter any issues. I will give it another try, but I agree that it would be much better if the setting was configurable.

**Comment by juan131** [comment] 2018-08-20 11:09
Hi,

We just released a new revision of this docker image (**4.0.1-r11**/**4.1.2-r4**). As you can check on the **README.md** file there's a new env. variable **MONGODB_ENABLE_IPV6** that can be used to enable/disable IPv6 on MongoDB configuration.

I also created [this PR](https://github.com/helm/charts/pull/7258) to include this feature on MongoDB chart so you can use the parameter **"mongodbEnableIPv6"** to configure your MongoDB chart with/without IPv6 enabled.

Please feel free to test it and close this issue if you considered it solved!

**Comment by ccojocar** [comment] 2018-08-20 15:43
@juan131 @sameersbn @tompizmor it seems this change breaks the docker image. I am getting this with `4.0.1-debian-9` release:

```
nami    INFO  Initializing mongodb
mongodb INFO  ==> Deploying MongoDB with persisted data...
mongodb INFO  ==> No injected configuration files found. Creating default config files...
mongodb INFO
mongodb INFO  ########################################################################
mongodb INFO   Installation parameters for mongodb:
mongodb INFO     Persisted data and properties have been restored.
mongodb INFO     Any input specified will not take effect.
mongodb INFO   This installation requires no credentials.
mongodb INFO  ########################################################################
mongodb INFO
nami    INFO  mongodb successfully initialized
INFO  ==> Starting mongodb...
INFO  ==> Starting mongod...
Expected boolean switch but found string:  for option: net.ipv6
try '/opt/bitnami/mongodb/bin/mongod --help' for more information
```

I think the value needs to be a boolean not "yes"/'no": 
https://docs.mongodb.com/manual/reference/configuration-options/#net-options

**Comment by juan131** [comment] 2018-08-20 15:54
Hi @ccojocar 

Could you share the **docker-compose.yaml** you're using?

**Comment by ccojocar** [comment] 2018-08-20 15:57
I am not using compose, but this helm chart https://github.com/helm/monocular/tree/master/deployment/monocular which is fetching the `stable/mongodb` chart which uses the image.tag `4.0.1-debian-9`.

**Comment by ccojocar** [comment] 2018-08-20 15:58
The version `4.0.1-debian-9-r10` works fine.

**Comment by juan131** [comment] 2018-08-20 16:08
I was unable to reproduce it using `docker-compose.yaml` and the version `4.0.1-debian-9`. Using the env. variable MONGODB_ENABLE_IPV6 I could enable/disable IPv6.

Using the chart, as you can check on the line below:

https://github.com/helm/charts/blob/master/stable/mongodb/templates/statefulset-primary-rs.yaml#L86

It transforms the chart parameter which is a boolean (true/false) into a string (yes/no) which is later used by Nami initialisation to setup the MongoDB configuration file.

I think it could be related with the persisted data...

```
mongodb INFO  ==> Deploying MongoDB with persisted data...
mongodb INFO  ==> No injected configuration files found. Creating default config files...
```

Let me debut it and I'll ping you asap with more info

**Comment by juan131** [comment] 2018-08-20 16:17
Hi @ccojocar 

Issue identified and I'm already working on releasing a new image fixing it. 

The env. variable is only being taken into account on Nami logic when deploying from scratch but it's not using it properly when initialising MongoDB with persisted data. 

I'll update the issue as soon as the new image is released. Thanks for reporting it.

**Comment by drunkhacker** [comment] 2018-08-20 16:42
@juan131 I just got the exact same error when I try new image. Hope new release come out soon. Cheer up!

**Comment by juan131** [comment] 2018-08-20 17:33
Hi everyone,

I just released the version *4.0.1-debian-9-r12*, *4.0.1-r12* which address this issue. Could you please give it a try?

**Comment by ebalsumgo** [comment] 2018-08-20 23:01
this seems to be working for me now. The one thing that seemingly broke (but I think i have to open on the helm repo) is the arbiter is now not working and seemingly reading the root password

**Comment by juan131** [comment] 2018-08-21 07:01
Could you open a different issue for that @ebalsumgo ? I'd rather stick to the topic on this issue in order to avoid confusion.

**Comment by juan131** [comment] 2018-08-21 08:00
Hi @ccojocar 

We're using rolling tags on the chart. Find more information on the link below:
https://docs.bitnami.com/containers/how-to/understand-rolling-tags-containers/

Therefore, if you run:

```
docker pull bitnami/mongodb:4.0.1-debian-9-r12
docker pull bitnami/mongodb:4.0.1-debian-9
docker images --digests | grep bitnami/mongodb
```

You'd find that both images are the same since **4.0.1-debian-9** points to the latest version (which is currently **4.0.1-debian-9-r12**)

**Comment by juan131** [comment] 2018-08-21 08:33
We released the rest of the versions pending to be released with the patch that fixes the issue:

- 4.1-debian-9
- 4.1.2-debian-9
- 4.1.2-debian-9-r5
- 4.1
- 4.1.2
- 4.1.2-r5
- 4.0-debian-9
- 4.0.1-debian-9
- 4.0.1-debian-9-r12
- 4.0
- 4.0.1
- 4.0.1-r12
- 3.6-debian-9
- 3.6.6-debian-9
- 3.6.6-debian-9-r38
- 3.6
- 3.6.6
- 3.6.6-r38

I proceed to close this issue. Please feel free to reopen it if you face issues with IPv6 using this image!

**Closed by juan131** 2018-08-21 08:33 UTC

**Comment by ccojocar** [comment] 2018-08-21 08:37
The `3.6.6-debian-9` still seems to fail.

**Comment by ccojocar** [comment] 2018-08-21 08:38
```
kubectl logs -f jenkins-x-mongodb-7dd488d47b-276vq

Welcome to the Bitnami mongodb container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues

nami    INFO  Initializing mongodb
mongodb INFO  ==> Deploying MongoDB with persisted data...
mongodb INFO  ==> No injected configuration files found. Creating default config files...
mongodb INFO
mongodb INFO  ########################################################################
mongodb INFO   Installation parameters for mongodb:
mongodb INFO     Persisted data and properties have been restored.
mongodb INFO     Any input specified will not take effect.
mongodb INFO   This installation requires no credentials.
mongodb INFO  ########################################################################
mongodb INFO
nami    INFO  mongodb successfully initialized
INFO  ==> Starting mongodb...
INFO  ==> Starting mongod...
Expected boolean switch but found string:  for option: net.ipv6
try '/opt/bitnami/mongodb/bin/mongod --help' for more information
```

```
kubectl get pods -oyaml jenkins-x-mongodb-7dd488d47b-276vq
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: 2018-08-21T08:32:00Z
  generateName: jenkins-x-mongodb-7dd488d47b-
  labels:
    app: mongodb
    chart: mongodb-4.0.4
    pod-template-hash: "3880448036"
    release: jenkins-x
  name: jenkins-x-mongodb-7dd488d47b-276vq
  namespace: jx
  ownerReferences:
  - apiVersion: extensions/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: jenkins-x-mongodb-7dd488d47b
    uid: ac6b2da4-a51c-11e8-bc37-42010a84012c
  resourceVersion: "4211574"
  selfLink: /api/v1/namespaces/jx/pods/jenkins-x-mongodb-7dd488d47b-276vq
  uid: ac808aa9-a51c-11e8-bc37-42010a84012c
spec:
  containers:
  - env:
    - name: MONGODB_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          key: mongodb-root-password
          name: jenkins-x-mongodb
    - name: MONGODB_USERNAME
    - name: MONGODB_DATABASE
      value: monocular
    - name: MONGODB_EXTRA_FLAGS
    image: docker.io/bitnami/mongodb:3.6.6-debian-9
    imagePullPolicy: Always```

**Comment by ccojocar** [comment] 2018-08-21 08:40
@juan131 The issue is not completely solved.

**Comment by ccojocar** [comment] 2018-08-21 08:46
It seems to be fixed now. It took a bit of time until the latest version of the image was served.

**Comment by juan131** [comment] 2018-08-21 08:52
Hi @ccojocar 

Could you share the Digest of the **bitnami/mongodb:3.6.6-debian-9** you're using?

**Comment by juan131** [comment] 2018-08-21 08:54
Hi @ccojocar 

I just saw your last message!! Just.... I wrote the post just after releasing that tag and I guess it took some time to your K8s cluster to pull the latest version. Could we consider it solved then?

**Comment by ccojocar** [comment] 2018-08-21 08:54
It works now, it took some time until Docker Hub served the new version of the image.

**Comment by ccojocar** [comment] 2018-08-21 08:55
Yes

**Comment by juan131** [comment] 2018-08-21 08:57
All right! Glad to hear that! 😃

**Comment by carrodher** [comment] 2019-07-04 07:06
We released a [new MongoDB chart version](https://github.com/helm/charts/pull/15229) (`stable/mongodb 6.0.0`) disabling IPv6 by default in order to fix some issues related to IPv6 in certain environments, as you can see in the description, depending on the way in which IPv6 is disabled in the host, the mongodb service could fail if it is configured to support this protocol by setting `net.ipv6: true` in the _mongodb.conf_ file.

In the same way, the `bitnami/mongodb` image will have the `MONGODB_ENABLE_IPV6 ` env. variable disabled by default [since the latest versions](https://github.com/bitnami/bitnami-docker-mongodb#3613-r33-4010-r42-4113-r40-and-4113-r41).

Please, feel free to ping me if you find some issues with the new approach.
