### ISSUE TITLE
Not clear how mongod is run

### ISSUE THREAD

**Issue by whitecolor** [bitnami/bitnami-docker-mongodb#62] opened 2017-01-26 10:03 UTC
To me It is not completely clear the bitnami abstraction for running `mongod` and how env variables are handled. How is it possible to know which exact commands does container runs? particular `mongod` with what arguments?

How for example `MONGODB_ROOT_PASSWORD` is handled etc. I see https://github.com/bitnami/bitnami-docker-mongodb/blob/master/rootfs/mongodb-inputs.json this file that maps env variables to some params hash, but these params do not look like `mongod` arguments.

Want fully understand how image works, how it reacts on env variables change while start/restart/etc.

**Comment by je-al** [comment] 2017-01-26 12:39
"+1". I'm specifically interested in what's the behavior when the master's persistent storage / volume vanishes.

**Comment by prydonius** [comment] 2017-01-26 23:21
Hey @whitecolor @je-al,

First off, I'm sorry that the way this image works is not clear. I want to assure you that we know this is a problem, we've been discussing it a lot internally, and we are planning on doing a lot to improve the visibility of our images in the coming weeks. Our goal is to make it easy for people to use, understand, and customise our images. Your feedback will definitely help us improve, so please file issues, or contact us (containers@bitnami.com) if you have any suggestions or concerns.

To configure and run MongoDB, we make use of [nami](https://github.com/bitnami/nami) and the existing MongoDB package for nami, which is fetched and installed using the `bitnami-pkg` helper (https://github.com/bitnami/bitnami-docker-mongodb/blob/master/Dockerfile#L12).

Unfortunately, today the source of the MongoDB package is not being published anywhere, and the only way to read it is to unpack the [tarball of the release](https://downloads.bitnami.com/files/stacksmith/mongodb-3.4.1-1-linux-x64-debian-8.tar.gz), but I've uploaded the main logic in this gist: https://gist.github.com/prydonius/f9c92389916f046635db07d231fe449c.

> How is it possible to know which exact commands does container runs? particular mongod with what arguments?

The container runs `nami start mongodb` which gets mapped to `mongod --config /bitnami/mongodb/conf/mongodb.conf` as specified in the manifest: https://gist.github.com/prydonius/f9c92389916f046635db07d231fe449c#file-bitnami-json-L106.

> How for example MONGODB_ROOT_PASSWORD is handled etc. I see https://github.com/bitnami/bitnami-docker-mongodb/blob/master/rootfs/mongodb-inputs.json this file that maps env variables to some params hash, but these params do not look like mongod arguments.

This file is used to map env vars to the properties used by the package, which are defined in the manifest: https://gist.github.com/prydonius/f9c92389916f046635db07d231fe449c#file-bitnami-json-L31.

The inputs file is provided when the package is initialised, which is done in the entrypoint: https://github.com/bitnami/bitnami-docker-mongodb/blob/master/rootfs/app-entrypoint.sh#L12.

> Want fully understand how image works, how it reacts on env variables change while start/restart/etc.

The `nami initialize` command from the entrypoint runs the [postInstallation function in the main.js file of the package](https://gist.github.com/prydonius/f9c92389916f046635db07d231fe449c#file-main-js-L7). The initialisation logic will only handle user creation, replica configuration, etc. on the first run - as this configuration is persisted (https://gist.github.com/prydonius/f9c92389916f046635db07d231fe449c#file-main-js-L15). When the container is restarted or recreated with the same volume, the already persisted data is 'restored' (symlinked), and so env variable changes will be ignored (https://gist.github.com/prydonius/f9c92389916f046635db07d231fe449c#file-main-js-L40).

> I'm specifically interested in what's the behavior when the master's persistent storage / volume vanishes.

If the persistent volume is removed and the container is restarted/recreated, the master will reinitialize itself using the env vars provided. I'm not entirely sure how this will affect the rest of the cluster as I'm not all that familiar with MongoDB replication (but perhaps @sameersbn knows more).

**Comment by je-al** [comment] 2017-01-27 12:46
@prydonius thanks for the detailed response. And yes, it's precisely the way it handles being launched configured as a _master_ when a _replica set_ was previously initialized (and therefore, a new master now exists) which could be problematic.

**Comment by sameersbn** [comment] 2017-01-30 16:00
@je-al if the master data volume is deleted the cluster will effective loose its data and state. Isn't this the expected mongo behaviour? How do you expect the cluster to react when this occurs?

**Comment by je-al** [comment] 2017-02-02 15:41
@sameersbn well, no, It *could* lose some data (i.e. non replicated writes), but the whole point of having a replicaset is that the data is replicated and the default behaviour (and depending on the types of members configured might not succeed, but that's another issue) is that the remaining members will perform an election for a _new_ master.

**Comment by eljefedelrodeodeljefe** [comment] 2017-08-17 03:05
Can you please work on that? Otherwise I would like to file issues to get those images out of helm charts. This all seems very opinionated.

**Comment by whitecolor** [comment] 2017-08-17 11:39
> Otherwise I would like to file issues to get those images out of helm charts. 

This sounds dangerous =)

To me, those (bitnami) images seem opinionated too, I use my own charts based on official MongoDB docker image.

**Comment by dbarranco** [comment] 2017-08-18 17:36
Hi @je-al

Apologies for the delay on my answer.
Based on the latest answer you posted here, I think that would not be possible. Let me explain why:

Let’s suppose we have a cluster with 1 primary, 2 secondaries and 1 arbiter, for example.
If that cluster is running fine and the master goes down the process to elect a new master will start. I manually checked that in our `docker-compose-replicaset.yml` doing a docker-compose up of the default docker-compose file and using a `docker kill ID` to kill the container that has the master.

Now, if you instance another docker-compose with this inside:

```version: '2'

services:
  mongodb-primary:
    image: 'bitnami/mongodb:latest'
    environment:
      - MONGODB_REPLICA_SET_MODE=primary
    volumes:
      - 'mongodb_master_otherdata:/bitnami'

volumes:
  mongodb_master_otherdata:
    driver: local
networks:
  default:
    external:
      name: mongotest_default
```

Will attach another primary node in the same network and will take the IP address than the previous master had.
The important thing here is that each cluster has a **replica set ID**, so the ID from the new master and the current master of the cluster will be different and it won’t be connected to the current cluster that is working.
You will get in the logs some errors like this:

```mongodb-secondary_1  | 2017-08-18T16:06:04.251+0000 I REPL     [ReplicationExecutor] Error in heartbeat request to 172.23.0.2:27017; InvalidReplicaSetConfig: replica set IDs do not match, ours: 599709f3c0aa5e612ed6bfba; remote node's: 59970a3e900b05439edfb570
mongodb-arbiter_1    | 2017-08-18T16:06:04.421+0000 I REPL     [ReplicationExecutor] Error in heartbeat request to 172.23.0.2:27017; InvalidReplicaSetConfig: replica set IDs do not match, ours: 599709f3c0aa5e612ed6bfba; remote node's: 59970a3e900b05439edfb570
```

So your cluster will keep the data that it current has without any loose.

Furthermore, as following the [mongoDB documentation](https://docs.mongodb.com/manual/tutorial/expand-replica-set/#requirements):

> If the new member is in a recovering state, it must exit and become a secondary before MongoDB can copy all data as part of the replication process. This process takes time but does not require administrator intervention.

If you are going to add a new member in the cluster, it will  have to be a secondary one. I also don’t see the case in which you add another primary to the cluster.

If you need more information about adding new members to the cluster you can take a look at the [Official documentation of MongoDB](https://docs.mongodb.com/manual/tutorial/expand-replica-set/).

Best regards,
David Barranco.

**Comment by tompizmor** [comment] 2017-09-06 16:12
@je-al ,  I tried to reproduce the issue but I didn’t experience the loss of data. Here you can find the steps I followed:

Start deploy
```
$ docker-compose -f docker-compose-replicaset.yml up
```

Scale some secondaries nodes
```
$ docker-compose -f docker-compose-replicase.yml scale mongoldb-secondary=3
```

Create some content in the primary
```
PRIMARY> db.example.insert({“msg”:”First message from original primary”})
```

Check that the content is being replicated by connecting to a secondary node and executing this commands:

```
SECONDARY> rs.slaveOk()
SECONDARY> db.example.find()
```

Now stop the primary to force the re-election:
```
$ docker stop <primary_container_id>
```

At this point the rest of nodes elect a new primary:

Insert more data in the new elected primary.
```
PRIMARY> db.example.insert({“msg”:”Message from new elected primary”})
```

Start the original primary
```
$ docker start  <primary_container_id>
```

The cluster adjusts itself so the original primary is primary again and the previously elected primary goes back to a secondary role.

The data inserted while the original primary was stopped exists in the original primary.

```
PRIMARY> db.example.find()
{ "_id" : ObjectId("59b00c966fc06940bce2e584"), "msg" : "First message from original primary" }
{ "_id" : ObjectId("59b00d166b5ee1c066291359"), "msg" : "Message from new elected primary" }
```

Are you experiencing something different? If so, would you mind telling us how to reproduce it?

However, I’ve found an issue after running docker-compose down/up. The nodes are configured by IP so if the IP of the container change after a down/up a secondary node can appear as an arbiter or vice-versa. I guess we should configure the nodes by its service name (which is preserved between down/up operation) 

-------
@eljefedelrodeodeljefe , several topics have been covered in this issue. Would you mind telling us what would you like to see in the bitnami/mongodb docker image?

**Comment by je-al** [comment] 2017-09-09 03:06
What @whitecolor and then myself were asking for was a clarification of how the image behaved, I'm not suggesting it's doing anything wrong.

What I referred to in my previous post (https://github.com/bitnami/bitnami-docker-mongodb/issues/62#issuecomment-276992443) was that I was *curious* about the behavior of the image when launched with the primary configuration when it had no data (because its volume disappeared), but a replica set already existed.

The reason is that from the steps outlined in the README it might *seem* like new secondaries connect to the container to which the configured environment variables point them to, therefore, a container launched with the "primary" configuration must exist for new members to join the cluster automatically, which means that if for some reason it were to die, and it might happen that it also lost its volume, a new one should be launched, which would have no notion of the existing replica set.

@tompizmor in your example you just stopped the primary container, you didn't delete it (which means it kept its IP, and so, other members of the cluster know about it), nor its data (which means it knows about the replica set). The initialization scripts probably check for the existence of data in mongodb's data dir in order to avoid attempting a replica set initialization, but we don't know, 'cause what they do isn't documented. And, yes, if the replica set is configured to use IPs instead of service names that's a problem, but there's really no way around it unless you want to create a new "service" per instance, instead of "scaling" them (which brings along a bunch of other possible issues).

@dbarranco read above about "adding" "primaries", again, that in your example the new "primary" can't (/won't/shouldn't) connect to the existing replica set is exactly the sort of stuff that should be documented. And, no, it will not *necessarily* take the IP of the old master back, there's no explicit IP assignment in that configuration. And, no, I did not say there was / I had an issue. And, this is actually not what I talked about, I was referring to stopping and removing the "primary" from the "original" compose file, and then re-creating it; which, from your example, appears like it would result in it creating a replica set of its own, which new scaled secondaries would join, instead of the old one.
 
p.s.: I'm not trying to be difficult, and it has been so long that I don't even recall if I actually tried to read the scripts inside the image, I just added a +1 when I was on the lookout for a Docker Mongo image that handled auto-configuration, and responded to a question...

**Comment by tompizmor** [comment] 2017-09-12 14:46
Hi again @je-al , 
Thanks for taking the time to reply back and clarify this issue.

> What I referred to in my previous post (#62 (comment)) was that I was curious about the behavior of the image when launched with the primary configuration when it had no data (because its volume disappeared), but a replica set already existed.

In that case, if you kill the primary node, delete the volume and then recreate it again within the same network, there are two things that can happen:
	- If the new primary gets the IP of the old primary, the cluster adjusts itself and recover their original state.
	- If this new primary gets an IP that the current replica set is not aware of, then it will start a new replica set only with a primary node.

> The reason is that from the steps outlined in the README it might seem like new secondaries connect to the container to which the configured environment variables point them to, therefore, a container launched with the "primary" configuration must exist for new members to join the cluster automatically, which means that if for some reason it were to die, and it might happen that it also lost its volume, a new one should be launched, which would have no notion of the existing replica set.

You can add new secondaries to the cluster by pointing the MONGODB_PRIMARY_HOST env var to the current primary in the cluster. It is not necessary that the container would have been launched with primary configuration.

> The initialization scripts probably check for the existence of data in mongodb's data dir in order to avoid attempting a replica set initialization, but we don't know, 'cause what they do isn't documented

Exactly. The initialization scripts check for the existence of a `.initialized` file in the `/bitnami/mongodb` folder. If the file is there, then the image skip the initialization and just recover the data from the volume.

From our part, we have added the following information to our README so hopefully is a bit more clear the way replicas are configured.

https://github.com/bitnami/bitnami-docker-mongodb#how-is-a-replica-set-configured

**Comment by tompizmor** [comment] 2017-09-21 10:24
Closing this issue. Please reopen if you consider further actions are needed.

**Closed by tompizmor** 2017-09-21 10:24 UTC

**Comment by AmandeepBhupal** [comment] 2020-10-27 16:39
> Hi @je-al
> 
> Apologies for the delay on my answer.
> Based on the latest answer you posted here, I think that would not be possible. Let me explain why:
> 
> Let’s suppose we have a cluster with 1 primary, 2 secondaries and 1 arbiter, for example.
> If that cluster is running fine and the master goes down the process to elect a new master will start. I manually checked that in the`docker-compose-replicaset.yml` doing a docker-compose up of the default docker-compose file and using a `docker kill ID` to kill the container that has the master.
> 
> Now, if you instance another docker-compose with this inside:
> 
> ```
> 
> services:
>   mongodb-primary:
>     image: 'bitnami/mongodb:latest'
>     environment:
>       - MONGODB_REPLICA_SET_MODE=primary
>     volumes:
>       - 'mongodb_master_otherdata:/bitnami'
> 
> volumes:
>   mongodb_master_otherdata:
>     driver: local
> networks:
>   default:
>     external:
>       name: mongotest_default
> ```
> 
> Will attach another primary node in the same network and will take the IP address than the previous master had.
> The important thing here is that each cluster has a **replica set ID**, so the ID from the new master and the current master of the cluster will be different and it won’t be connected to the current cluster that is working.
> You will get in the logs some errors like this:
> 
> ```
> mongodb-arbiter_1    | 2017-08-18T16:06:04.421+0000 I REPL     [ReplicationExecutor] Error in heartbeat request to 172.23.0.2:27017; InvalidReplicaSetConfig: replica set IDs do not match, ours: 599709f3c0aa5e612ed6bfba; remote node's: 59970a3e900b05439edfb570
> ```
> 
> So your cluster will keep the data that it current has without any loose.
> 
> Furthermore, as following the [mongoDB documentation](https://docs.mongodb.com/manual/tutorial/expand-replica-set/#requirements):
> 
> > If the new member is in a recovering state, it must exit and become a secondary before MongoDB can copy all data as part of the replication process. This process takes time but does not require administrator intervention.
> 
> If you are going to add a new member in the cluster, it will have to be a secondary one. I also don’t see the case in which you add another primary to the cluster.
> 
> If you need more information about adding new members to the cluster you can take a look at the [Official documentation of MongoDB](https://docs.mongodb.com/manual/tutorial/expand-replica-set/).
> 
> By our part, we will look to improve the container solution, hope this post can clarify your doubts. :)
> 
> Best regards,
> David Barranco.

For me this process requires admin intervention. Mongodb is not taking care of this on its own. getting this error: [ReplicationExecutor] Error in heartbeat request to 172.23.0.2:27017; InvalidReplicaSetConfig: replica set IDs do not match, ours: 599709f3c0aa5e612ed6bfba; remote node's: 59970a3e900b05439edfb570
