### ISSUE TITLE
mount persistent volumn fail

### ISSUE THREAD

**Issue by 4haohansen2033** [bitnami/bitnami-docker-mongodb#170] opened 2019-09-06 03:50 UTC
Hi.
I am trying to use rancher to install mongodb.  pod will restart fail when config persistent volume. 
Error message:

```
nami INFO Initializing mongodb
mongodb INFO ==> Deploying MongoDB from scratch...
mongodb INFO ==> No injected configuration files found. Creating default config files...
Error executing 'postInstallation': EACCES: permission denied, mkdir '/bitnami/mongodb/data'
```
if I don't mount volume, the pod will start success. i can find data directory `/bitnami/mongodb/db/data` in container

**Steps to reproduce the issue:**

**Comment by carrodher** [comment] 2019-09-06 08:13
Hi, I will try to reproduce the issue, can you share with us your _docker-compose.yml_?

**Comment by 4haohansen2033** [comment] 2019-09-06 08:56
@carrodher  sorry. I‘m afraid I can’t supply the config.  but k8s  schedule deployment to start container image of pod . so docker-compose.yml doesn't exist. 
The error message make me confuse that can't find relation code in libmongodb.sh

**Comment by carrodher** [comment] 2019-09-10 07:16
Can you run the following commands and share here the output?
- `kubectl get pvc`
```
$ kubectl get pvc
NAME                   STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
edgy-hamster-mongodb   Bound    pvc-3432e13a-d39a-11e9-981a-42010a96013a   8Gi        RWO            standard       17s`
```
- `kubectl describe pvc edgy-hamster-mongodb`
- `kubectl describe pv pvc-3432e13a-d39a-11e9-981a-42010a96013a`

Take into account you need to replace `edgy-hamster-mongodb` and `pvc-3432e13a-d39a-11e9-981a-42010a96013a` by the values obtained in your specific case via the first command.

Apart from that, can you share some hints about how did you deploy the application? Running `helm install stable/mongodb` I am not able to reproduce the issue.

**Comment by 4haohansen2033** [comment] 2019-09-10 07:47
@carrodher thx sharing.  the issue had resolved. i modify the directory permissions that map to container of volumn. now it's work.
chown :root /opt/data && chmod g+rwX /opt/data

**Comment by carrodher** [comment] 2019-09-10 08:01
Great, that is one of the side effects of using [non-root containers](https://docs.bitnami.com/containers/how-to/work-with-non-root-containers/). We are glad that you were able to fix the issue. I am closing this issue. If you have any other questions, please do not hesitate to let us know.

**Closed by carrodher** 2019-09-10 08:01 UTC

**Comment by veera2019** [comment] 2019-10-28 05:27
i have installed mongodb using helm install stable/mongodb command after installing that mongodb pod status showing crashloopbackoff and i have seen logs it's showing error like mkdir: cannot create directory '/bitnami/mongodb/data': Permission denied.
I am installing mongodb on kubernetes in windows environment 
Error message 
[38;5;6m [38;5;5m05:25:28.91 [0m
[38;5;6m [38;5;5m05:25:28.92 [0m[1mWelcome to the Bitnami mongodb container[0m
[38;5;6m [38;5;5m05:25:28.92 [0mSubscribe to project updates by watching [1mhttps://github.com/bitnami/bitnami-docker-mongodb[0m
[38;5;6m [38;5;5m05:25:28.92 [0mSubmit issues and feature requests at [1mhttps://github.com/bitnami/bitnami-docker-mongodb/issues[0m
[38;5;6m [38;5;5m05:25:28.92 [0mSend us your feedback at [1mcontainers@bitnami.com[0m
[38;5;6m [38;5;5m05:25:28.92 [0m
[38;5;6m [38;5;5m05:25:28.92 [0m[38;5;2mINFO [0m ==> ** Starting MongoDB setup **
[38;5;6m [38;5;5m05:25:28.93 [0m[38;5;2mINFO [0m ==> Validating settings in MONGODB_* env vars...
[38;5;6m [38;5;5m05:25:28.93 [0m[38;5;2mINFO [0m ==> Initializing MongoDB...
[38;5;6m [38;5;5m05:25:28.93 [0m[38;5;2mINFO [0m ==> Deploying MongoDB from scratch...
mkdir: cannot create directory '/bitnami/mongodb/data': Permission denied

Somebody can give me the solution

**Comment by carrodher** [comment] 2019-10-28 10:52
Is there an existing PVC attached to the mongo pod?
```
kubectl get pvc
```
If yes, can you try again removing the existing PVC?
