### ISSUE TITLE
Collection not found after docker-compose down - up

### ISSUE THREAD

**Issue by AstaDK** [bitnami/bitnami-docker-mongodb#269] opened 2021-06-27 03:23 UTC
```yml
version: "3.7"

services:
  node:
    container_name: demo-server
    build:
      context: .
      dockerfile: ./dockers/Dockerfile
    ports:
      - 3200:3000
    volumes:
      - .:/app
    command: yarn start
    networks:
      - common
    env_file:
      - .env
    links:
      - mongo

  mongo:
    container_name: demo-mongo
    image: bitnami/mongodb:4.4
    restart: always
    env_file:
      - .env
    environment:
      - MONGODB_ROOT_USERNAME=${MONGODB_ROOT_USERNAME}
      - MONGODB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
      - MONGODB_USERNAME=${MONGODB_ROOT_PASSWORD}
      - MONGODB_PASSWORD=${MONGODB_ROOT_PASSWORD}
      - MONGODB_DATABASE=${MONGODB_DATABASE}
    ports:
      - 27017:27017
    volumes:
      - ./mongodb_data:/bitnami/mongodb
    networks:
      - common

  mongo-express:
    container_name: demo-mongo-express
    image: mongo-express
    restart: always
    env_file:
      - .env
    environment:
      - ME_CONFIG_MONGODB_SERVER=video-hosting-mongo
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
      - ME_CONFIG_MONGODB_AUTH_DATABASE=${MONGODB_DATABASE}
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGODB_ROOT_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGODB_ROOT_PASSWORD}
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGODB_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGODB_PASSWORD}
      - ME_CONFIG_MONGODB_AUTH_USERNAME=${MONGODB_USERNAME}
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=${MONGODB_PASSWORD}
    depends_on:
      - mongo
    ports:
      - 8081:8081
    networks:
      - common

networks:
  common:
  
volumes:
  mongo:
    name: demo
```

This is my config about mongo-express vs Bitnami MongoDB.
I facing the issue after I act with DB in order to create a user, video ... it means I have records in my DB but **after I down and up again I can not find collect that according to the document will mount**
The image below after I down and up docker-compose and click user collection:
![Screen Shot 2021-06-27 at 10 21 41](https://user-images.githubusercontent.com/80238484/123531776-9bab5b80-d731-11eb-9b4a-468a62931648.png)

**Comment by AstaDK** [comment] 2021-06-27 03:29
@sameersbn

**Comment by AstaDK** [comment] 2021-06-27 03:58
FIY: I saw a message maybe relate this err above but I'm not sure:

> {"t":{"$date":"2021-06-27T03:49:48.948+00:00"},"s":"E",  "c":"STORAGE",  "id":22435,   "ctx":"conn1","msg":"WiredTiger error","attr":{"error":1,"message":"[1624765788:948242][1:0x7f7710b4a700], file:collection-0--1931751418316133436.wt, WT_SESSION.open_cursor: __posix_open_file, 808: /bitnami/mongodb/data/db/collection-0--1931751418316133436.wt: handle-open: open: Operation not permitted"}}

**Comment by Mauraza** [comment] 2021-06-28 10:47
Hi @AstaDK,

could you check the permission of the `./mongodb_data`?

**Comment by AstaDK** [comment] 2021-06-29 14:43
@Mauraza this is my permission file:
![Screen Shot 2021-06-29 at 21 43 06](https://user-images.githubusercontent.com/80238484/123818284-0d96c700-d923-11eb-93bf-9b4fb0c0e9ee.png)

**Comment by Mauraza** [comment] 2021-06-30 06:53
Hi @AstaDK,

In your docker-compose.yaml appears:
```yaml
volumes:
      - ./mongodb_data:/bitnami/mongodb
```
That folder has the data, did you have a folder with the name mongodb_data? 
Could you check this part of the README.md https://github.com/bitnami/bitnami-docker-mongodb/#persisting-your-database?

**Comment by Mauraza** [comment] 2021-07-01 07:54
Hi @AstaDK,

the volume you are mounting does not have the proper permissions for the non-root user to create files and directories. You would need to make the permissions more open by using `chmod`.

> NOTE: As this is a non-root container, the mounted files and directories must have the proper permissions for the UID 1001.

**Comment by AstaDK** [comment] 2021-07-01 17:44
hi @Mauraza, Stepping that I do after read your mention:
- docker-compose down
- removing volume
- removing folder mongoldb-persistence
- creating new folder mongoldb-persistence

then I used this command: 
> sudo chmod -R g+rwx mongoldb-persistence

- docker-up --build 
- add data to collection (added)

- docker-down
- docker-up => worked, the data still appear collection

**BUT**
I down compose again and then docker-compose up => the error occurred
I don't know why the error appears with the second try

`video-hosting-mongo | {"t":{"$date":"2021-07-01T17:38:03.434+00:00"},"s":"E",  "c":"STORAGE",  "id":22435,   "ctx":"conn1","msg":"WiredTiger error","attr":{"error":1,"message":"[1625161083:434690][1:0x7f227d3e2700], file:collection-0-178636324173396121.wt, WT_SESSION.open_cursor: __posix_open_file, 808: /bitnami/mongodb/data/db/collection-0-178636324173396121.wt: handle-open: open: Operation not permitted"}}
video-hosting-mongo | {"t":{"$date":"2021-07-01T17:38:03.434+00:00"},"s":"F",  "c":"STORAGE",  "id":50882,   "ctx":"conn1","msg":"Failed to open WiredTiger cursor. This may be due to data corruption","attr":{"uri":"table:collection-0-178636324173396121","config":"","error":{"code":8,"codeName":"UnknownError","errmsg":"1: Operation not permitted"},"message":"Please read the documentation for starting MongoDB with --repair here: http://dochub.mongodb.org/core/repair"}}
video-hosting-mongo | {"t":{"$date":"2021-07-01T17:38:03.434+00:00"},"s":"F",  "c":"-",        "id":23091,   "ctx":"conn1","msg":"Fatal assertion","attr":{"msgid":50882,"file":"src/mongo/db/storage/wiredtiger/wiredtiger_session_cache.cpp","line":109}}
video-hosting-mongo | {"t":{"$date":"2021-07-01T17:38:03.434+00:00"},"s":"F",  "c":"-",        "id":23092,   "ctx":"conn1","msg":"\n\n***aborting after fassert() failure\n\n"}`

**Comment by Mauraza** [comment] 2021-07-02 08:02
Hi @AstaDK,

It seems in this case you have data corruption. Have you tried to follow the MongoDB documentation to repair the data?

**Comment by AstaDK** [comment] 2021-07-02 08:05
I only create new recort for a collection and then I down and up docker-compose => the error occur.

**Comment by AstaDK** [comment] 2021-07-03 11:21
Having any update?

**Comment by Mauraza** [comment] 2021-07-05 12:01
Hi @AstaDK, 

I have not been able to reproduce it. Could you try to give more permission to the folder?

**Comment by AstaDK** [comment] 2021-07-06 15:26
you can see permission at image
![Screen Shot 2021-07-06 at 22 18 20](https://user-images.githubusercontent.com/80238484/124626357-cb343380-dea8-11eb-9045-f3502da4cc6f.png)

More version:
- Docker version: 20.10.7, build f0df350
- docker-compose version" 1.29.2, build 5becea4c
- macOS Bis Sur: 11.0.1

Permission inside a docker bash:
![Screen Shot 2021-07-06 at 22 25 34](https://user-images.githubusercontent.com/80238484/124626805-3120bb00-dea9-11eb-8005-66bff1635aaf.png)

![Screen Shot 2021-07-06 at 22 26 13](https://user-images.githubusercontent.com/80238484/124626818-354cd880-dea9-11eb-9dfa-89f388072dab.png)

**Comment by Mauraza** [comment] 2021-07-07 07:46
Hi @AstaDK,

I see some of the collection and the index have differents permission, could you put all with the same and the owner?
```bash
sudo chown -R 1001:root mongodb-persistence
```

**Comment by AstaDK** [comment] 2021-07-09 17:06
Thank a lot. It worked for me.

**Comment by Mauraza** [comment] 2021-07-12 08:01
Hi @AstaDK,

I'm glad the problem is solved. Closing this out now, do not hesitate to write us back if you have any other questions.

**Closed by Mauraza** 2021-07-12 08:01 UTC
